### ISSUE TITLE
Incorrect errors from StardogSparqlParser with some Stardog functions

### ISSUE THREAD

**Issue by jmrog** [stardog-union/millan#28]
Stardog provides support for XPath math functions. The parser correctly handles all of them _except_ for the ones that start with "a" (asin, acos, atan). This is almost definitely a token-ordering issue.

Example that produces the error:

```sparql
select * {
  bind(atan(1) as ?s)
}
```

**Comment by jbalint** [comment]
let's work together as the fix is likely the same for stardog-union/stardog#7324
