### ISSUE TITLE
SrsParser defers to "W3C Spec" SPARQL parser rather than "Stardog" SPARQL parser

### ISSUE THREAD

**Issue by jmrog** [stardog-union/millan#42]
As an example, the following (valid) rule shows diagnostic errors, because the `date` function is not recognized:

```
PREFIX rule: <tag:stardog:api:rule:>

RULE rules:LeaseTerminatedEarlyRule
IF {
    ?l a ro:ActiveLease .
    ?lease_event ro:lease ?l ;
        a ro:LeaseEvent ;
        ops:EventDate ?event_dt ;
        rdfs:label ?event_name .
    BIND (IF(strstarts(?event_name, "Early Termination"), "true"^^xsd:boolean, "false"^^xsd:boolean) as ?terminated_early)
    BIND (date(?event_dt) as ?event_date)
}
THEN {
    ?l ro:terminatedEarly ?terminated_early ;
        ro:earlyTerminationDate ?event_date .
}
```

If we instead make the SRS parser defer to the StardogSparqlParser (rather than the W3CSpecSparqlParser), it won't show an error here.

**Comment by sfkrauss** [comment]
Jason and I chatted - not quick/straightforward, we don't expect a lot of people to hit this and it's not blocking, just a false alarm. Will keep our ears open for it but moving to backlog for now.
